logging:
  file:
    path: /home/zwl/idea/work-space/logs/ftc-shop/

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: zwl
    password: zwl
    virtual-host: /fct-shop
    listener:
      direct:
        # 手动 ack
        acknowledge-mode: manual
        # 开启重试，重试三次
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
    # 到达目标队列回调
    publisher-returns: true
    # 设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除
    template:
      mandatory: true
    # 到达交换机回调
    publisher-confirm-type: correlated


  redis:
    # Redis服务器地址
    host: 'localhost'
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    # Redis服务器连接密码（默认为空）
    password: 
    lettuce: # 使用 Lettuce 连接池
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000ms # 连接超时时间（毫秒）

#写入你的小程序信息
wx:
  miniapp:
    appid: wx9aab3fa657026fb1  #微信小程序的appid
    secret: 62cb388c56065eb9e6f0f21e3088c459 #微信小程序的Secret
    msgDataFormat: JSON

jwt:
  pvt-key-file-name: RSA.key
  pub-key-file-name: RSA.pub
  duration: 1800s  #JWT 30分钟过期
